# application.yml

spring:
  application:
    name: BootSecurity

  # 기본 실행 지정
  profiles:
    active: prod
    # 배포할 때 Docker를 사용해서 prod로 지정하기

  security:
    user:
      name: user
      password: 1234

  # 데이터베이스 연결 설정 - application-dev.yml
  datasource:
      # 커넥션 풀 관련
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 10 # 최대 커넥션 수
        minimum-idle: 5 # 최소 유휴 커넥션 수

  mybatis:
#    mapper-locations: classpath:mapper/*.xml # 매퍼 XML 파일 위치 설정
    type-aliases-package: org.example.bootsecurity.model.domain # 도메인 객체 패키지 경로
    configuration:
      map-underscore-to-camel-case: true # 언더스코어 표기법을 카멜 케이스 표기법으로 자동 변환

# 로깅 설정
logging:
  level:
    org.example.bootsecurity.mapper: DEBUG # mapper 패키지의 로깅 레벨을 DEBUG로 설정

#  logging.level.org.springframework.transaction=DEBUG
#  logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG # 좀 더 상세한 로그